# Generated by Django 2.0 on 2018-10-12 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_UPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('ups_model', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=10)),
                ('serial_number', models.CharField(max_length=30)),
                ('ups_date', models.DateField(default=None)),
                ('battery_brand', models.CharField(max_length=20)),
                ('battery_model', models.CharField(max_length=20)),
                ('battery_string', models.IntegerField()),
                ('battery_quantity', models.IntegerField()),
                ('battery_date', models.DateField()),
                ('input_cap_date', models.DateField()),
                ('output_cap_date', models.DateField()),
                ('dc_cap_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
