# Generated by Django 2.0 on 2018-10-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_part', models.CharField(max_length=10)),
                ('part_number', models.CharField(default=None, max_length=20)),
                ('values', models.CharField(default=None, max_length=10)),
                ('description', models.CharField(blank=True, default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10)),
                ('model_ups', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UPS_Part_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('parts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
                ('ups', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parts.UPS')),
            ],
        ),
    ]
