# Generated by Django 2.0 on 2018-10-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='part',
            name='values',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
